package service

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"

	"halo/backend/internal/model"
	"halo/backend/internal/repository"
)

// PhotoUploadService handles photo upload URL generation and record creation.
type PhotoUploadService struct {
	photoRepo *repository.PhotoRepository
	s3Bucket  string
	urlExpiry time.Duration
}

// NewPhotoUploadService creates a new PhotoUploadService.
func NewPhotoUploadService(
	photoRepo *repository.PhotoRepository,
	s3Bucket string,
	urlExpiry time.Duration,
) *PhotoUploadService {
	return &PhotoUploadService{
		photoRepo: photoRepo,
		s3Bucket:  s3Bucket,
		urlExpiry: urlExpiry,
	}
}

// UploadURLRequest is the input for requesting a presigned upload URL.
type UploadURLRequest struct {
	UserID      string
	ContentType string // image/jpeg, image/png, image/webp
}

// UploadURLResponse is the response with the presigned URL.
type UploadURLResponse struct {
	UploadURL string    `json:"upload_url"`
	ObjectKey string    `json:"object_key"`
	ExpiresAt time.Time `json:"expires_at"`
}

// S3 object key format:
//   photos/{userID}/originals/{photoID}.{ext}
//
// Variant keys (generated by Lambda):
//   photos/{userID}/variants/{photoID}_blur_heavy.webp
//   photos/{userID}/variants/{photoID}_blur_med.webp
//   photos/{userID}/variants/{photoID}_blur_light.webp
//   photos/{userID}/variants/{photoID}_clear.webp

// extensionForContentType maps content type to file extension.
func extensionForContentType(ct string) string {
	switch ct {
	case "image/jpeg":
		return "jpg"
	case "image/png":
		return "png"
	case "image/webp":
		return "webp"
	default:
		return "jpg"
	}
}

// GenerateObjectKey builds the S3 object key for an original photo upload.
func GenerateObjectKey(userID, photoID, contentType string) string {
	ext := extensionForContentType(contentType)
	return fmt.Sprintf("photos/%s/originals/%s.%s", userID, photoID, ext)
}

// VariantObjectKey builds the S3 object key for a generated variant.
func VariantObjectKey(userID, photoID, variant string) string {
	return fmt.Sprintf("photos/%s/variants/%s_%s.webp", userID, photoID, variant)
}

// ValidContentTypes is the allowed set of content types for photo uploads.
var ValidContentTypes = map[string]bool{
	"image/jpeg": true,
	"image/png":  true,
	"image/webp": true,
}

// CreateUploadURL generates a presigned S3 PUT URL and creates the photo record.
//
// NOTE: In production, this would call the AWS SDK to generate a presigned URL.
// For MVP, we generate the object key and record, and the actual presigning
// would be done by an S3 presigner (not wired here since it requires AWS creds).
func (s *PhotoUploadService) CreateUploadURL(ctx context.Context, req *UploadURLRequest) (*UploadURLResponse, *model.Photo, error) {
	if !ValidContentTypes[req.ContentType] {
		return nil, nil, fmt.Errorf("unsupported content type: %s (allowed: %s)",
			req.ContentType, strings.Join(allowedTypes(), ", "))
	}

	photoID := uuid.New().String()
	objectKey := GenerateObjectKey(req.UserID, photoID, req.ContentType)

	// Create photo record in DB (processing_status = 'pending').
	photo, err := s.photoRepo.Create(ctx, req.UserID, objectKey, req.ContentType, true)
	if err != nil {
		return nil, nil, fmt.Errorf("create photo record: %w", err)
	}

	expiresAt := time.Now().Add(s.urlExpiry)

	// In production, generate a presigned S3 PUT URL here.
	// For MVP, we return a placeholder URL that the client would use.
	uploadURL := fmt.Sprintf("https://%s.s3.amazonaws.com/%s", s.s3Bucket, objectKey)

	return &UploadURLResponse{
		UploadURL: uploadURL,
		ObjectKey: objectKey,
		ExpiresAt: expiresAt,
	}, photo, nil
}

func allowedTypes() []string {
	types := make([]string, 0, len(ValidContentTypes))
	for t := range ValidContentTypes {
		types = append(types, t)
	}
	return types
}
